# Tikpal Pi4 kiosk baseline
--enable-pinch
--start-fullscreen
--window-size=2560,720
--window-position=0,0
--no-first-run
--no-default-browser-check
--noerrdialogs
--disable-infobars
--disable-session-crashed-bubble
--autoplay-policy=no-user-gesture-required
--disable-features=UseOzonePlatform,MediaRouter,Translate,OptimizationHints,AutofillServerCommunication,CertificateTransparencyComponentUpdater
--ozone-platform=x11

# App-only browser noise reduction
--disable-background-networking
--disable-background-timer-throttling
--disable-component-update
--disable-default-apps
--disable-domain-reliability
--disable-popup-blocking
--disable-renderer-backgrounding
--disable-sync
--metrics-recording-only
--no-pings
