export const FLOW_ORDER = ["focus", "flow", "relax", "sleep"];

export const FLOW_THEME = {
  focus: {
    label: "FOCUS",
    subtitle: "Deep Work",
    bgGradient: ["#081421", "#10294A", "#1D3D73"],
    accent: "#5B7CFF",
    glow: "#7C8DFF",
    motionStyle: "linear_wave",
    motionSpeed: 0.35,
    motionAmplitude: 0.22,
    particleDensity: 0.08,
    uiTone: "sharp",
  },
  relax: {
    label: "RELAX",
    subtitle: "Wind Down",
    bgGradient: ["#1A1311", "#5A2E24", "#C46D4A"],
    accent: "#FFB38A",
    glow: "#FF8FA8",
    motionStyle: "fluid_cloud",
    motionSpeed: 0.18,
    motionAmplitude: 0.35,
    particleDensity: 0.12,
    uiTone: "soft",
  },
  sleep: {
    label: "SLEEP",
    subtitle: "Night Drift",
    bgGradient: ["#020305", "#050812", "#0B1020"],
    accent: "#6C7A9C",
    glow: "#2C3550",
    motionStyle: "near_static",
    motionSpeed: 0.04,
    motionAmplitude: 0.05,
    particleDensity: 0.01,
    uiTone: "dim",
  },
  flow: {
    label: "FLOW",
    subtitle: "Motion Loop",
    bgGradient: ["#0C1020", "#392C6D", "#8A4D88"],
    accent: "#8E7CFF",
    glow: "#FF7DB8",
    motionStyle: "layered_wave",
    motionSpeed: 0.28,
    motionAmplitude: 0.42,
    particleDensity: 0.16,
    uiTone: "floating",
  },
};
